### ISSUE TITLE
README/examples lacking information for tools.deps users

### ISSUE THREAD

**Issue by jleonard-r7** [oliyh/kamera#26]
Hi,

Can you please explain how a `deftest` in a clj file is being picked up in your example project? I've tried emulating your setup with my figwheel main + tools.deps environment but it is not picking up the .clj test. I suspect that the difference could be between leiningen vs tools.deps although your leiningen file (project.clj) also looks pretty bland and relatively equivalent to what I have with tools.deps.

Any help would be much appreciated.

Thank you,
Jonathan

**Comment by jleonard-r7** [comment]
I believe I can make do with:

a) a new separate, pure Clojure, main entry in my deps.edn.
b) a separate test runner that merely calls `clojure.test/run-all-tests` (which in your case, is being done automatically by leiningen).

**Comment by oliyh** [comment]
Hi,

Yes, lein includes `./test` as the default test path, and I believe you are correct in what `lein test` does. Kamera is a library to help you write tests, how you actually run them is up to you but is pretty standard across all Clojure build tools.

If you would like to contribute a working deps.edn to the example project I'd be happy to include it.

Cheers

**Comment by jleonard-r7** [comment]
This: https://github.com/oliyh/kamera/issues/26#issuecomment-722708059 worked.

No need for PR I think but if you wanted to make it clear how this is operating (i.e., aside from leiningen magic which hides the actual mechanism from tools.deps users), you'd simply do what I mentioned above. You could even do it with the existing "lein" implementation just to make it explicit what's actually happening.

If you really think a PR is necessary, I can give it a shot. For now, leaving this as a breadcrumb and closing the issue.
